from enter import *
from db import *
from main import *
#from root_panel import *
#from admin_panel import *
#from user_Panel import *
#from pass_recov import *
#from Quizgame import *
#from set_recov import *
#from user_regis import *
from testfunct import *
